alias v='vim'
alias gdb='gdb -q'
alias c='clear'
alias ipy='ipython'
alias irc='ssh nebel@lolbox.pwnies.dk -t screen -dr irc'
alias ida='wine ~/ida66/idaq.exe'
alias ida64='wine ~/ida66/idaq64.exe'
alias net='~/repos/net/net'
alias g11='g++ -std=c++11'
alias i='sudo apt-get install'
alias livestreamer='livestreamer --http-header Client-ID=jzkbprff40iqj646a697cyrvl0zt2m6 --player=mpv'
alias irb='irb --readline -r irb/completion'
alias hs='hoogle search --color --count=10'
alias hi='hoogle search --color -info'
